<?xml version="1.0" encoding="utf-8"?><Database Name="CUAHANGDIENTHOAI" Class="CUAHANGDIENTHOAIDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=MSI\SQLEXPRESS;Initial Catalog=CUAHANGDIENTHOAI;User ID=sa" SettingsObjectName="BLL.Properties.Settings" SettingsPropertyName="CUAHANGDIENTHOAIConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tb_Cart" Member="tb_Carts">
    <Type Name="tb_Cart">
      <Column Name="CartId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="IdKhachHang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tb_Cart_tb_CartItem" Member="tb_CartItems" ThisKey="CartId" OtherKey="CartId" Type="tb_CartItem" />
      <Association Name="tb_KhachHang_tb_Cart" Member="tb_KhachHang" ThisKey="IdKhachHang" OtherKey="IdKhachHang" Type="tb_KhachHang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_CartItem" Member="tb_CartItems">
    <Type Name="tb_CartItem">
      <Column Name="CartItem" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CartId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="PriceTotal" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="TemPrice" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="ProductDetailId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="tb_Cart_tb_CartItem" Member="tb_Cart" ThisKey="CartId" OtherKey="CartId" Type="tb_Cart" IsForeignKey="true" />
      <Association Name="tb_ProductDetail_tb_CartItem" Member="tb_ProductDetail" ThisKey="ProductDetailId" OtherKey="ProductDetailId" Type="tb_ProductDetail" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_ExportWareHouse" Member="tb_ExportWareHouses">
    <Type Name="tb_ExportWareHouse">
      <Column Name="ExportWareHouseId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Modifeby" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NhanVienId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OrderId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="WarehouseId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tb_Order_tb_ExportWareHouse" Member="tb_Order" ThisKey="OrderId" OtherKey="OrderId" Type="tb_Order" IsForeignKey="true" />
      <Association Name="tb_Warehouse_tb_ExportWareHouse" Member="tb_Warehouse" ThisKey="WarehouseId" OtherKey="WarehouseId" Type="tb_Warehouse" IsForeignKey="true" />
      <Association Name="tb_Staff_tb_ExportWareHouse" Member="tb_Staff" ThisKey="NhanVienId" OtherKey="NhanVienId" Type="tb_Staff" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_Function" Member="tb_Functions">
    <Type Name="tb_Function">
      <Column Name="IdChucNang" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TenChucNang" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MaChucNang" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Modifeby" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="tb_Function_tb_Role" Member="tb_Roles" ThisKey="IdChucNang" OtherKey="IdChucNang" Type="tb_Role" />
      <Association Name="tb_Function_tb_Staff" Member="tb_Staffs" ThisKey="IdChucNang" OtherKey="IdChucNang" Type="tb_Staff" />
    </Type>
  </Table>
  <Table Name="dbo.tb_ImportWarehouse" Member="tb_ImportWarehouses">
    <Type Name="tb_ImportWarehouse">
      <Column Name="ImportWarehouseId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="CreateDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Modifeby" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NhanVienId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProductDetailId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="QuanTity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="WarehouseId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tb_ProductDetail_tb_ImportWarehouse" Member="tb_ProductDetail" ThisKey="ProductDetailId" OtherKey="ProductDetailId" Type="tb_ProductDetail" IsForeignKey="true" />
      <Association Name="tb_Warehouse_tb_ImportWarehouse" Member="tb_Warehouse" ThisKey="WarehouseId" OtherKey="WarehouseId" Type="tb_Warehouse" IsForeignKey="true" />
      <Association Name="tb_Staff_tb_ImportWarehouse" Member="tb_Staff" ThisKey="NhanVienId" OtherKey="NhanVienId" Type="tb_Staff" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_KhachHang" Member="tb_KhachHangs">
    <Type Name="tb_KhachHang">
      <Column Name="IdKhachHang" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="TenKhachHang" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Image" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Birthday" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SoLanMua" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Code" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="Clock" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="tb_KhachHang_tb_Cart" Member="tb_Carts" ThisKey="IdKhachHang" OtherKey="IdKhachHang" Type="tb_Cart" />
      <Association Name="tb_KhachHang_tb_OrderDetail" Member="tb_OrderDetails" ThisKey="IdKhachHang" OtherKey="IdKhachHang" Type="tb_OrderDetail" />
      <Association Name="tb_KhachHang_tb_Return" Member="tb_Returns" ThisKey="IdKhachHang" OtherKey="IdKhachHang" Type="tb_Return" />
      <Association Name="tb_KhachHang_tb_ReviewDetail" Member="tb_ReviewDetails" ThisKey="IdKhachHang" OtherKey="IdKhachHang" Type="tb_ReviewDetail" />
    </Type>
  </Table>
  <Table Name="dbo.tb_Order" Member="tb_Orders">
    <Type Name="tb_Order">
      <Column Name="OrderId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="CustomerName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="TotalAmount" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Modifiedby" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TypePayment" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="typeOrder" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="[Confirm]" Member="Confirm" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="typeReturn" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Success" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SuccessDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IdKhachHang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tb_Order_tb_ExportWareHouse" Member="tb_ExportWareHouses" ThisKey="OrderId" OtherKey="OrderId" Type="tb_ExportWareHouse" />
      <Association Name="tb_Order_tb_OrderDetail" Member="tb_OrderDetails" ThisKey="OrderId" OtherKey="OrderId" Type="tb_OrderDetail" />
      <Association Name="tb_Order_tb_Return" Member="tb_Returns" ThisKey="OrderId" OtherKey="OrderId" Type="tb_Return" />
      <Association Name="tb_Order_tb_Voucher" Member="tb_Vouchers" ThisKey="OrderId" OtherKey="OrderId" Type="tb_Voucher" />
    </Type>
  </Table>
  <Table Name="dbo.tb_OrderDetail" Member="tb_OrderDetails">
    <Type Name="tb_OrderDetail">
      <Column Name="OrderDetailId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CartItem" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DamagedProduct" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="OrderId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdKhachHang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProductDetailId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tb_KhachHang_tb_OrderDetail" Member="tb_KhachHang" ThisKey="IdKhachHang" OtherKey="IdKhachHang" Type="tb_KhachHang" IsForeignKey="true" />
      <Association Name="tb_Order_tb_OrderDetail" Member="tb_Order" ThisKey="OrderId" OtherKey="OrderId" Type="tb_Order" IsForeignKey="true" />
      <Association Name="tb_ProductDetail_tb_OrderDetail" Member="tb_ProductDetail" ThisKey="ProductDetailId" OtherKey="ProductDetailId" Type="tb_ProductDetail" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_ProductCompany" Member="tb_ProductCompanies">
    <Type Name="tb_ProductCompany">
      <Column Name="ProductCompanyId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Modifeby" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Alias" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Icon" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Association Name="tb_ProductCompany_tb_Product" Member="tb_Products" ThisKey="ProductCompanyId" OtherKey="ProductCompanyId" Type="tb_Product" />
    </Type>
  </Table>
  <Table Name="dbo.tb_ProductCategory" Member="tb_ProductCategories">
    <Type Name="tb_ProductCategory">
      <Column Name="ProductCategoryId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Icon" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Modifiedby" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Alias" Type="System.String" DbType="NVarChar(150) NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="tb_ProductCategory_tb_Product" Member="tb_Products" ThisKey="ProductCategoryId" OtherKey="ProductCategoryId" Type="tb_Product" />
    </Type>
  </Table>
  <Table Name="dbo.tb_ProductDetail" Member="tb_ProductDetails">
    <Type Name="tb_ProductDetail">
      <Column Name="ProductDetailId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Color" Type="System.String" DbType="NVarChar(40)" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="PriceSale" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="OrigianlPrice" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="TypeProduct" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Image" Type="System.String" DbType="NVarChar(900)" CanBeNull="true" />
      <Column Name="DungLuongPin" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Ram" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DungLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProductsId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tb_ProductDetail_tb_CartItem" Member="tb_CartItems" ThisKey="ProductDetailId" OtherKey="ProductDetailId" Type="tb_CartItem" />
      <Association Name="tb_ProductDetail_tb_ImportWarehouse" Member="tb_ImportWarehouses" ThisKey="ProductDetailId" OtherKey="ProductDetailId" Type="tb_ImportWarehouse" />
      <Association Name="tb_ProductDetail_tb_OrderDetail" Member="tb_OrderDetails" ThisKey="ProductDetailId" OtherKey="ProductDetailId" Type="tb_OrderDetail" />
      <Association Name="tb_ProductDetail_tb_ProductDetailImage" Member="tb_ProductDetailImages" ThisKey="ProductDetailId" OtherKey="ProductDetailId" Type="tb_ProductDetailImage" />
      <Association Name="tb_ProductDetail_tb_Review" Member="tb_Reviews" ThisKey="ProductDetailId" OtherKey="ProductDetailId" Type="tb_Review" />
      <Association Name="tb_Product_tb_ProductDetail" Member="tb_Product" ThisKey="ProductsId" OtherKey="ProductsId" Type="tb_Product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_ProductDetailImage" Member="tb_ProductDetailImages">
    <Type Name="tb_ProductDetailImage">
      <Column Name="ProductImageId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductDetailId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Image" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="IsDefault" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="tb_ProductDetail_tb_ProductDetailImage" Member="tb_ProductDetail" ThisKey="ProductDetailId" OtherKey="ProductDetailId" Type="tb_ProductDetail" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_ProductImage" Member="tb_ProductImages">
    <Type Name="tb_ProductImage">
      <Column Name="ProductImageId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductsId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Image" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="IsDefault" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="tb_Product_tb_ProductImage" Member="tb_Product" ThisKey="ProductsId" OtherKey="ProductsId" Type="tb_Product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_Return" Member="tb_Returns">
    <Type Name="tb_Return">
      <Column Name="ReturnId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[Confirm]" Member="Confirm" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="OrderId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdKhachHang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Satus" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="tb_Return_tb_ReturnDetail" Member="tb_ReturnDetails" ThisKey="ReturnId" OtherKey="ReturnId" Type="tb_ReturnDetail" />
      <Association Name="tb_KhachHang_tb_Return" Member="tb_KhachHang" ThisKey="IdKhachHang" OtherKey="IdKhachHang" Type="tb_KhachHang" IsForeignKey="true" />
      <Association Name="tb_Order_tb_Return" Member="tb_Order" ThisKey="OrderId" OtherKey="OrderId" Type="tb_Order" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_Products" Member="tb_Products">
    <Type Name="tb_Product">
      <Column Name="ProductsId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Modifeby" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Alias" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsHome" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsSale" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsFeature" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsHot" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SeoTitle" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="SeoDescription" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ProductCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="KichCo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TocDoCPU" Type="System.String" DbType="NVarChar(900)" CanBeNull="true" />
      <Column Name="HeDieuHanh" Type="System.String" DbType="NVarChar(900)" CanBeNull="true" />
      <Column Name="TocDoGPU" Type="System.String" DbType="NVarChar(900)" CanBeNull="true" />
      <Column Name="MangDiDong" Type="System.String" DbType="NVarChar(900)" CanBeNull="true" />
      <Column Name="Sim" Type="System.String" DbType="Char(900)" CanBeNull="true" />
      <Column Name="Wifi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="GPS" Type="System.String" DbType="NVarChar(900)" CanBeNull="true" />
      <Column Name="Bluetooth" Type="System.String" DbType="Char(900)" CanBeNull="true" />
      <Column Name="CongKetNoi" Type="System.String" DbType="NVarChar(900)" CanBeNull="true" />
      <Column Name="JackTaiNghe" Type="System.String" DbType="NVarChar(900)" CanBeNull="true" />
      <Column Name="LoaiPin" Type="System.String" DbType="Char(900)" CanBeNull="true" />
      <Column Name="HoTroSac" Type="System.String" DbType="NVarChar(900)" CanBeNull="true" />
      <Column Name="CongNghePin" Type="System.String" DbType="NVarChar(900)" CanBeNull="true" />
      <Column Name="Image" Type="System.String" DbType="NVarChar(900)" CanBeNull="true" />
      <Column Name="CPU" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="GPU" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="ManHinh" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="ProductCategoryId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProductCompanyId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tb_Product_tb_ProductDetail" Member="tb_ProductDetails" ThisKey="ProductsId" OtherKey="ProductsId" Type="tb_ProductDetail" />
      <Association Name="tb_Product_tb_ProductImage" Member="tb_ProductImages" ThisKey="ProductsId" OtherKey="ProductsId" Type="tb_ProductImage" />
      <Association Name="tb_Product_tb_ReturnDetail" Member="tb_ReturnDetails" ThisKey="ProductsId" OtherKey="ProductsId" Type="tb_ReturnDetail" />
      <Association Name="tb_ProductCompany_tb_Product" Member="tb_ProductCompany" ThisKey="ProductCompanyId" OtherKey="ProductCompanyId" Type="tb_ProductCompany" IsForeignKey="true" />
      <Association Name="tb_ProductCategory_tb_Product" Member="tb_ProductCategory" ThisKey="ProductCategoryId" OtherKey="ProductCategoryId" Type="tb_ProductCategory" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_ReturnDetail" Member="tb_ReturnDetails">
    <Type Name="tb_ReturnDetail">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ReturnId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductsId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tb_Product_tb_ReturnDetail" Member="tb_Product" ThisKey="ProductsId" OtherKey="ProductsId" Type="tb_Product" IsForeignKey="true" />
      <Association Name="tb_Return_tb_ReturnDetail" Member="tb_Return" ThisKey="ReturnId" OtherKey="ReturnId" Type="tb_Return" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_Review" Member="tb_Reviews">
    <Type Name="tb_Review">
      <Column Name="ReviewId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Modifeby" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ProductDetailId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tb_Review_tb_ReviewDetail" Member="tb_ReviewDetails" ThisKey="ReviewId" OtherKey="ReviewId" Type="tb_ReviewDetail" />
      <Association Name="tb_ProductDetail_tb_Review" Member="tb_ProductDetail" ThisKey="ProductDetailId" OtherKey="ProductDetailId" Type="tb_ProductDetail" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_Warehouse" Member="tb_Warehouses">
    <Type Name="tb_Warehouse">
      <Column Name="WarehouseId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Modifeby" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="StoreId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tb_Warehouse_tb_ExportWareHouse" Member="tb_ExportWareHouses" ThisKey="WarehouseId" OtherKey="WarehouseId" Type="tb_ExportWareHouse" />
      <Association Name="tb_Warehouse_tb_ImportWarehouse" Member="tb_ImportWarehouses" ThisKey="WarehouseId" OtherKey="WarehouseId" Type="tb_ImportWarehouse" />
      <Association Name="tb_Store_tb_Warehouse" Member="tb_Store" ThisKey="StoreId" OtherKey="StoreId" Type="tb_Store" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_ReviewDetail" Member="tb_ReviewDetails">
    <Type Name="tb_ReviewDetail">
      <Column Name="ReviewDetailId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Modifeby" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Content" Type="System.String" DbType="NVarChar(350)" CanBeNull="true" />
      <Column Name="ReviewId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdKhachHang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tb_KhachHang_tb_ReviewDetail" Member="tb_KhachHang" ThisKey="IdKhachHang" OtherKey="IdKhachHang" Type="tb_KhachHang" IsForeignKey="true" />
      <Association Name="tb_Review_tb_ReviewDetail" Member="tb_Review" ThisKey="ReviewId" OtherKey="ReviewId" Type="tb_Review" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_Role" Member="tb_Roles">
    <Type Name="tb_Role">
      <Column Name="NhanVienId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IdChucNang" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="tb_Function_tb_Role" Member="tb_Function" ThisKey="IdChucNang" OtherKey="IdChucNang" Type="tb_Function" IsForeignKey="true" />
      <Association Name="tb_Staff_tb_Role" Member="tb_Staff" ThisKey="NhanVienId" OtherKey="NhanVienId" Type="tb_Staff" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_Staff" Member="tb_Staffs">
    <Type Name="tb_Staff">
      <Column Name="NhanVienId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MSNV" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="TenNhanVien" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="CCCD" Type="System.String" DbType="Char(12) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Image" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Birthday" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="NgayVaoLam" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Luong" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(7)" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedBy" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Clock" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IdChucNang" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tb_Staff_tb_ExportWareHouse" Member="tb_ExportWareHouses" ThisKey="NhanVienId" OtherKey="NhanVienId" Type="tb_ExportWareHouse" />
      <Association Name="tb_Staff_tb_ImportWarehouse" Member="tb_ImportWarehouses" ThisKey="NhanVienId" OtherKey="NhanVienId" Type="tb_ImportWarehouse" />
      <Association Name="tb_Staff_tb_Role" Member="tb_Roles" ThisKey="NhanVienId" OtherKey="NhanVienId" Type="tb_Role" />
      <Association Name="tb_Function_tb_Staff" Member="tb_Function" ThisKey="IdChucNang" OtherKey="IdChucNang" Type="tb_Function" IsForeignKey="true" />
      <Association Name="tb_StaffImage_tb_Staff" Member="tb_StaffImage" ThisKey="NhanVienId" OtherKey="Id" Type="tb_StaffImage" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb_StaffImage" Member="tb_StaffImages">
    <Type Name="tb_StaffImage">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Image" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="IsDefault" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="NhanVienId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="tb_StaffImage_tb_Staff" Member="tb_Staff" ThisKey="Id" OtherKey="NhanVienId" Type="tb_Staff" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.tb_Store" Member="tb_Stores">
    <Type Name="tb_Store">
      <Column Name="StoreId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Modifiedby" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Alias" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="DiChi" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="District" Type="System.String" DbType="NVarChar(60)" CanBeNull="true" />
      <Column Name="IsStatus" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="tb_Store_tb_Warehouse" Member="tb_Warehouses" ThisKey="StoreId" OtherKey="StoreId" Type="tb_Warehouse" />
    </Type>
  </Table>
  <Table Name="dbo.tb_Voucher" Member="tb_Vouchers">
    <Type Name="tb_Voucher">
      <Column Name="VoucherId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Code" Type="System.String" DbType="Char(30)" CanBeNull="true" />
      <Column Name="PhanTramGiam" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Modifeby" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UsedBy" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="UsedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OrderId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="tb_Order_tb_Voucher" Member="tb_Order" ThisKey="OrderId" OtherKey="OrderId" Type="tb_Order" IsForeignKey="true" />
    </Type>
  </Table>
</Database>